### PR TITLE
Update to support postcss v5 syntax

### PR DESCRIPTION
**Pull request by lukelarsen**

### CODE REVIEW

**Comment by lukelarsen** [comment]
I'd love to use this plugin. It just needs to be updated to the newer v5 syntax.

**Comment by ojame** [comment]
Awesome :+1:

**Comment by lukelarsen** [comment]
Any chance we can get npm updated to have the latest?

**Comment by ojame** [comment]
Done! https://www.npmjs.com/package/postcss-constants

Looks like this introduces the need for Promise in node, so you'll need 11.3x or higher (or something like that!)

Thanks again.

**Comment by lukelarsen** [comment]
Np. Thanks for making the plugin.

**Pull request merged**
